namespace UsernameGenerator
{
    internal static class Resources
    {
        internal static string[] Adjectives = new string[]
        {
            "Abrasive", "Adorable", "Adult", "Agile", "Agreeable", "Ambitious", "Amiable", "Amusing", "Ancient", "Angry",
            "Anxious", "Aquatic", "Assertive", "Astute", "Athletic", "Audacious", "Avian", "Awkward", "Bashful",
            "Beautiful", "Bizarre", "Blind", "Bold", "Brave", "Bright", "Brutish", "Bulky", "Busy", "Calm", "Carefree",
            "Careful", "Careless", "Caring", "Cautious", "Charming", "Cheeky", "Cheerful", "Chirping", "Chunky",
            "Clever", "Clumsy", "Coarse", "Colorful", "Comical", "Confident", "Confused", "Content", "Cowardly",
            "Crafty", "Croaking", "Cuddly", "Cunning", "Curious", "Dainty", "Daring", "Dark", "Dauntless", "Dazzling",
            "Deaf", "Deceptive", "Defeated", "Delicate", "Demanding", "Dignified", "Dirty", "Discreet", "Diurnal",
            "Docile", "Dominant", "Dramatic", "Dreary", "Drowsy", "Dutiful", "Dynamic", "Eager", "Earthy", "Eccentric",
            "Ecstatic", "Edgy", "Efficient", "Elated", "Elegant", "Elongated", "Energetic", "Enigmatic", "Enormous",
            "Epic", "Equable", "Erratic", "Exotic", "Faithful", "Fearless", "Feeble", "Feral", "Ferocious", "Fetal",
            "Fickle", "Fierce", "Flexible", "Fluffy", "Foolhardy", "Forceful", "Frail", "Friendly", "Frisky", "Frugal",
            "Furry", "Gallant", "Gaunt", "Gentle", "Giant", "Gigantic", "Glamorous", "Gleaming", "Glorious", "Graceful",
            "Gracious", "Grand", "Grateful", "Greedy", "Grim", "Grouchy", "Growling", "Gruesome", "Grumpy", "Gullible",
            "Hairy", "Handsome", "Happy", "Hardy", "Harmless", "Harsh", "Helpful", "Helpless", "Heroic", "Hilarious",
            "Hissing", "Holy", "Homey", "Honorable", "Hooting", "Hopeful", "Horrific", "Howling", "Hulking", "Humble",
            "Humorous", "Hungry", "Hypnotic", "Immense", "Infantile", "Insistent", "Intense", "Itchy", "Jealous",
            "Jolly", "Jovial", "Jubilant", "Juvenile", "Keen", "Kind", "Klutzy", "Knightly", "Knowing", "Lanky", "Lazy",
            "Lean", "Lithe", "Lively", "Lonely", "Lovable", "Loving", "Loyal", "Lucky", "Majestic", "Marvelous",
            "Massive", "Mature", "Meek", "Melodic", "Meowing", "Merciful", "Mighty", "Mild", "Miniature", "Mooing",
            "Muscular", "Mystical", "Naive", "Nasty", "Natural", "Neat", "Nervous", "Newborn", "Nice", "Noble",
            "Nocturnal", "Noisy", "Obedient", "Oblivious", "Obnoxious", "Observant", "Obsessive", "Odd", "Outgoing",
            "Overjoyed", "Palatial", "Panicked", "Panoramic", "Patient", "Peaceful", "Peculiar", "Perky", "Petite",
            "Pitiful", "Playful", "Pleasant", "Plucky", "Poisonous", "Polite", "Ponderous", "Portly", "Powerful",
            "Precise", "Predatory", "Premature", "Prideful", "Pristine", "Proud", "Puny", "Purring", "Puzzled",
            "Quacking", "Quaint", "Quick", "Quiet", "Radiant", "Rampant", "Rapid", "Rare", "Rascally", "Rash", "Refined",
            "Regal", "Relaxed", "Reliable", "Remote", "Repulsive", "Resilient", "Restless", "Roaring", "Robust", "Rough",
            "Rugged", "Ruthless", "Sacred", "Sagacious", "Salty", "Sassy", "Savage", "Scaly", "Scarce", "Scared",
            "Scary", "Scrappy", "Scrawny", "Secluded", "Sedate", "Seemly", "Selfish", "Senile", "Sensible", "Sensitive",
            "Sensual", "Serene", "Shaggy", "Sharp", "Shrewd", "Shy", "Silly", "Sincere", "Sinister", "Sizable",
            "Skillful", "Skittish", "Sleek", "Sleepy", "Slender", "Slick", "Sloppy", "Sly", "Small", "Smiling", "Smug",
            "Snappy", "Snug", "Sociable", "Soft", "Solid", "Solitary", "Somber", "Sorrowful", "Spacious", "Sparkling",
            "Speedy", "Spiky", "Spirited", "Spiteful", "Splendid", "Spooky", "Spotless", "Spotted", "Sprightly",
            "Spunky", "Squawking", "Stalwart", "Stealthy", "Stern", "Sticky", "Stinky", "Stocky", "Stoic", "Stolid",
            "Stout", "Strange", "Strapping", "Stressed", "Strict", "Striking", "Strong", "Stubborn", "Sturdy", "Sublime",
            "Subtle", "Sullen", "Swift", "Talented", "Tall", "Tame", "Tenacious", "Tender", "Terrified", "Testy",
            "Thankful", "Thrifty", "Thrilling", "Timid", "Tiny", "Tireless", "Tolerant", "Tough", "Towering", "Tranquil",
            "Trusting", "Truthful", "Turbulent", "Twitchy", "Ugly", "Ultimate", "Uncertain", "Unruly", "Unusual",
            "Uplifting", "Uptight", "Valiant", "Venomous", "Vibrant", "Vicious", "Vigilant", "Vile", "Violent",
            "Virtuous", "Viscous", "Vivacious", "Vocal", "Voracious", "Wailing", "Wary", "Watchful", "Weak", "Wealthy",
            "Weary", "Whimsical", "Wholesome", "Wild", "Willful", "Wise", "Wistful", "Witty", "Wobbly", "Wonderful",
            "Worried", "Worrisome", "Wrathful", "Wretched", "Wriggly", "Wry", "Youthful", "Zealous", "Zesty"
        };

        internal static string[] Animals = new string[]
        {
            "Agouti", "Akita", "Albatross", "Alligator", "Alpaca", "Amur", "Anaconda", "Angelfish", "Anhinga", "Ant",
            "Anteater", "Antelope", "Ape", "Aphid", "Armadillo", "Asp", "Axolotl", "Azawakh", "Baboon", "Badger",
            "Bandicoot", "Barb", "Barbel", "Barbet", "Barnacle", "Barracuda", "Basenji", "Bass", "Bat", "Beagle", "Bear",
            "Beauceron", "Beaver", "Bedbug", "Bee", "Beetle", "Biddy", "Binturong", "Bird", "Bison", "Blackbird",
            "Blindworm", "Bloodhound", "Bluebird", "Boa", "Boar", "Bobcat", "Boerboel", "Bolognese", "Bongo", "Bonobo",
            "Booby", "Borzoi", "Bovid", "Boxer", "Briard", "Brittany", "Buffalo", "Bull", "Bulldog", "Bullfrog",
            "Bullock", "Bushbaby", "Butterfly", "Buzzard", "Caiman", "Camel", "Canary", "Capybara", "Caracal",
            "Cardinal", "Caribou", "Carp", "Cat", "Catfish", "Cattle", "Cavachon", "Cavapoo", "Centaur", "Centipede",
            "Chameleon", "Chamois", "Cheetah", "Chicken", "Chihuahua", "Chimera", "Chimpanzee", "Chinchilla", "Chinook",
            "Chipmunk", "Chiton", "Clam", "Clownfish", "Coati", "Cobra", "Cockapoo", "Cockroach", "Cod", "Collie",
            "Condor", "Coonhound", "Coral", "Corgi", "Cormorant", "Cougar", "Cow", "Cowfish", "Coydog", "Coyote", "Crab",
            "Crane", "Cricket", "Crocodile", "Crow", "Cuckoo", "Dachshund", "Dalmatian", "Deer", "Dhole", "Dingo",
            "Dinosaur", "Dipper", "Doberman", "Dog", "Dolphin", "Donkey", "Dormouse", "Dove", "Dragon", "Dragonfly",
            "Duck", "Dugong", "Eagle", "Earwig", "Echidna", "Eel", "Egret", "Elephant", "Elk", "Emu", "Ermine", "Falcon",
            "Ferret", "Finch", "Firefly", "Fish", "Fisher", "Flamingo", "Flea", "Flounder", "Fly", "Fox", "Frog",
            "Frogspawn", "Gazelle", "Gecko", "Gerbil", "Gibbon", "Giraffe", "Gnat", "Goat", "Goby", "Goldador",
            "Goldfish", "Goose", "Gopher", "Gorilla", "Greyhound", "Groundhog", "Grouse", "Gull", "Guppy", "Haddock",
            "Halibut", "Hamster", "Hare", "Harrier", "Havanese", "Hawk", "Hedgehog", "Heron", "Herring", "Hornet",
            "Horse", "Human", "Hyena", "Ibis", "Iguana", "Impala", "Insect", "Jackal", "Jackdaw", "Jaguar", "Jay",
            "Jellyfish", "Jerboa", "Kangaroo", "Keeshond", "Kestrel", "Kite", "Kiwi", "Koala", "Komondor", "Krill",
            "Kuvasz", "Ladybug", "Lamprey", "Lemming", "Lemur", "Leopard", "Lion", "Lizard", "Llama", "Lobster",
            "Locust", "Lorikeet", "Lynx", "Lowchen", "Macaw", "Magpie", "Mallard", "Maltese", "Mammoth", "Manatee",
            "Mandrill", "Mantis", "Marlin", "Marmot", "Mastiff", "Mayfly", "Meerkat", "Mink", "Minnow", "Mole", "Molly",
            "Mongoose", "Monkey", "Moorhen", "Moose", "Moth", "Mouse", "Mule", "Muskrat", "Mussel", "Nandu", "Narwhal",
            "Nematode", "Newt", "Numbat", "Nuthatch", "Ocelot", "Octopus", "Okapi", "Opossum", "Orangutan", "Orca",
            "Ostrich", "Otter", "Owl", "Ox", "Oyster", "Panda", "Panther", "Papillon", "Parakeet", "Parrot", "Partridge",
            "Peacock", "Peafowl", "Pekingese", "Pelican", "Penguin", "Perch", "Pheasant", "Pig", "Pigeon", "Pike",
            "Pilchard", "Pinniped", "Piranha", "Plaice", "Planarian", "Platypus", "Plott", "Plover", "Pointer",
            "Polecat", "Pony", "Poodle", "Porcupine", "Porpoise", "Prawn", "Puffin", "Pug", "Puli", "Puma", "Pumi",
            "Python", "Quail", "Quetzal", "Rabbit", "Raccoon", "Racoon", "Ragdoll", "Ram", "Rat", "Raven", "Ray",
            "Reindeer", "Rhino", "Robin", "Rook", "Rooster", "Roundworm", "Sable", "Sailfish", "Salmon", "Saluki",
            "Samoyed", "Sandpiper", "Saola", "Sardine", "Saurian", "Sawfish", "Scallop", "Scorpion", "Seahorse", "Seal",
            "Serval", "Shark", "Sheep", "Shell", "Shrimp", "Siamese", "Skink", "Skunk", "Sloth", "Sloughi", "Slug",
            "Smelt", "Snail", "Snake", "Sparrow", "Spider", "Spoonbill", "Squid", "Squirrel", "Starfish", "Stingray",
            "Stork", "Sturgeon", "Swallow", "Swan", "Swift", "Swordfish", "Tadpole", "Tapir", "Tarantula", "Tarsier",
            "Termite", "Tetra", "Tiger", "Tit", "Toad", "Tortoise", "Toucan", "Trout", "Tuatara", "Turkey", "Turtle",
            "Uakari", "Uguisu", "Vervet", "Viper", "Vizsla", "Vole", "Vulture", "Wallaby", "Walrus", "Warbler", "Wasp",
            "Waterbuck", "Waterfowl", "Weasel", "Whale", "Whippet", "Wildcat", "Wolf", "Wolverine", "Wombat", "Worm",
            "Wren", "Xerus", "Yak", "Zander", "Zebra", "Zebrafish", "Zebu", "Zonkey", "Zorse"
        };
    }
}